// <auto-generated />
namespace ECommerce.Repository.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AdicioneiCampoPrecoEmProduto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdicioneiCampoPrecoEmProduto));
        
        string IMigrationMetadata.Id
        {
            get { return "201209221229215_AdicioneiCampoPrecoEmProduto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
