// <auto-generated />
namespace ECommerce.Repository.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Zero : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Zero));
        
        string IMigrationMetadata.Id
        {
            get { return "201209220228331_Zero"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
